language: go

sudo: false

go:
  - 1.7
  - tip

env:
  - GOARCH=amd64

install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/Masterminds/glide
  - go get -t -d ./...
  - glide up

script:
  - cd $HOME/gopath/src/github.com/apihub/apihub
  - make test

notifications:
  email:
    recipients:
      - albertonb@gmail.com

