web:
  build: .
  ports:
    - "8000:8000"
    - "8001:8001"
  links:
    - etcd
    - mongo
    - redis
etcd:
  image: quay.io/coreos/etcd
  command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
  ports:
    - "2379:2379"
    - "4001:4001"
mongo:
  image: mongo
  ports:
    - "27017:27017"
redis:
  image: redis
  ports:
    - "6379:6379"